CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'OPERATOR', 'READONLY');

ALTER TABLE "User" ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'OPERATOR';
ALTER TABLE "User" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;

UPDATE "User" SET "role" = 'ADMIN';
